id: 8346c763810e4398a44fffb954ea27ec
title: Toh_271-The_Eight_Buddhas-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-068-005
  eft-text-version: 1.1.5 2020
